import { Product, Category } from "@/types";

export const categories: Category[] = [
  { id: "1", name: "Scented Candles", slug: "scented" },
  { id: "2", name: "Unscented Candles", slug: "unscented" },
  { id: "3", name: "Gift Sets", slug: "gift-sets" },
  { id: "4", name: "Seasonal Collection", slug: "seasonal" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Vanilla Dream",
    slug: "vanilla-dream",
    description: "A warm and comforting vanilla scented candle that fills your space with sweet, creamy notes reminiscent of freshly baked cookies.",
    price: 599,
    images: ["/images/vanilla-dream.jpg"],
    category: categories[0],
    scent: "Vanilla",
    size: "Medium",
    burn_time: "40 hours",
    stock: 15,
    featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "2",
    name: "Lavender Fields",
    slug: "lavender-fields",
    description: "Transport yourself to the purple fields of Provence with this calming lavender scent, perfect for relaxation and stress relief.",
    price: 699,
    images: ["/images/lavender-fields.jpg"],
    category: categories[0],
    scent: "Lavender",
    size: "Large",
    burn_time: "60 hours",
    stock: 20,
    featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "3",
    name: "Ocean Breeze",
    slug: "ocean-breeze",
    description: "Fresh marine notes combined with hints of citrus create a refreshing coastal atmosphere in any room.",
    price: 549,
    images: ["/images/ocean-breeze.jpg"],
    category: categories[0],
    scent: "Marine & Citrus",
    size: "Medium",
    burn_time: "40 hours",
    stock: 12,
    featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "4",
    name: "Cinnamon Spice",
    slug: "cinnamon-spice",
    description: "Warm and inviting blend of cinnamon, nutmeg, and clove that creates a cozy ambiance perfect for autumn evenings.",
    price: 649,
    images: ["/images/cinnamon-spice.jpg"],
    category: categories[3],
    scent: "Spiced",
    size: "Large",
    burn_time: "55 hours",
    stock: 8,
    featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "5",
    name: "Rose Garden",
    slug: "rose-garden",
    description: "Delicate rose petals captured in wax, bringing the romance and elegance of a blooming garden indoors.",
    price: 799,
    images: ["/images/rose-garden.jpg"],
    category: categories[0],
    scent: "Rose",
    size: "Large",
    burn_time: "60 hours",
    stock: 10,
    featured: false,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "6",
    name: "Sandalwood Zen",
    slug: "sandalwood-zen",
    description: "Earthy sandalwood creates a meditative atmosphere, perfect for yoga sessions or quiet contemplation.",
    price: 899,
    images: ["/images/sandalwood-zen.jpg"],
    category: categories[0],
    scent: "Sandalwood",
    size: "XL",
    burn_time: "80 hours",
    stock: 5,
    featured: false,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
];